### ISSUE TITLE
Actual state of a command

### ISSUE THREAD

**Issue by phlegx** [ztzhang/GoProWifiCommand#2]
Hi!

Thank you for this list of commands. How can I get the actual state of a command? E.g. I want to know which primary modus is actually set.

**Comment by ztzhang** [comment]
Hi, I added a GetStatus command. You can send this request (http://10.5.5.9:8080/gp/gpControl/status) and decode the json returned. To decode, you may need to refer to the actual url. For example, to get resolution under video mode, you could look at ReturnedJson[settings][2]. I believe the Primary mode is [settings][0] and submode is [settings][1]
